language: android
# os: linux
# sudo: required
# jdk: oraclejdk8
dist: trusty


git:
  depth: 1

env:
  global:
  # - ANDROID_API_LEVEL=29
  # - ANDROID_BUILD_TOOLS_VERSION=29.0.1
  # - ANDROID_ABI=armeabi-v7a


android:
  components:
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-29.0.1
    - android-29

    # - add-on
    # - extra
    
    # Additional components
    # - extra-google-google_play_services
    # - extra-google-m2repository
    # - extra-android-m2repository

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    # - sys-img-x86-android-26
    # - sys-img-armeabi-v7a-android-17
  

  licenses:
    - 'android-sdk-preview-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    # White list all the licenses.
    - '.+'





before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

before_install:
    - touch $HOME/.android/repositories.cfg
    - export LANG=en_US.UTF-8
    - yes | sdkmanager "platforms;android-29"
    - yes | sdkmanager "build-tools;29.0.1"
    - yes | sdkmanager "build-tools;29.0.0"

script:
   - ./gradlew build