language: android
os: linux
sudo: required
jdk: oraclejdk8
dist: xenial


git:
  depth: 1

env:
  global:
  - ANDROID_API_LEVEL=29
  - ANDROID_BUILD_TOOLS_VERSION=29.0.1
  - ANDROID_ABI=armeabi-v7a


android:
  components:
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-29.0.1
    - android-29

    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'


before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

before_install:
    #- touch $HOME/.android/repositories.cfg
    #- yes | sdkmanager "platforms;android-28"
    #- yes | sdkmanager "build-tools;28.0.3"
    - export LANG=en_US.UTF-8
    - yes | sdkmanager "platforms;android-29"
    - yes | sdkmanager "build-tools;29.0.1"

script:
   - ./gradlew build